In [1]:
import numpy as np

In [4]:
# creating numpy with the lists
list = [1,5,4,3,2]
np.array(list)

array([1, 5, 4, 3, 2])

In [6]:
# Creating numpy with tuple
tuple = (1,5,4,3,2)
np.array(tuple)

array([1, 5, 4, 3, 2])

In [31]:
# To change the dtype of list
np.array(list,dtype=float)

array([1., 5., 4., 3., 2.])

In [30]:
np.array(list,dtype=str)

array(['1', '5', '4', '3', '2'], dtype='<U1')

In [34]:
# To change the dtype of a tuple
np.array(tuple,dtype=float)

array([1., 5., 4., 3., 2.])

In [36]:
np.array(tuple,dtype=str)

array(['1', '5', '4', '3', '2'], dtype='<U1')

In [16]:
string = 'Welcome to NumPy'

In [17]:
np.array(string)

array('Welcome to NumPy', dtype='<U16')

In [38]:
np.array(string,dtype='str')

array('Welcome to NumPy', dtype='<U16')

In [40]:
# numpy array of strings using list
np.array(['hello','welcome','NumPy'])
# Here 7 indicates maximum length of the string object

array(['hello', 'welcome', 'NumPy'], dtype='<U7')

In [41]:
# numpy array of strings using tuple
np.array(('hello','welcome','NumPy'))

array(['hello', 'welcome', 'NumPy'], dtype='<U7')

In [47]:
np.asarray(list)

array([1, 5, 4, 3, 2])

In [48]:
np.asarray(tuple)

array([1, 5, 4, 3, 2])

In [49]:
# creating NumPy using lists
lists = [[1,2,3],[2,3,1],[3,1,2]]
np.array(lists)

array([[1, 2, 3],
       [2, 3, 1],
       [3, 1, 2]])

In [50]:
# creating NumPy using tuples
tuples = ((1,2,3),(2,3,1),(3,1,2))
np.array(tuples)

array([[1, 2, 3],
       [2, 3, 1],
       [3, 1, 2]])

In [65]:
# creating sub copies of arrays
original = np.random.randint(1,6,size=(3,3))

In [66]:
original

array([[5, 2, 1],
       [5, 1, 3],
       [4, 3, 1]])

In [67]:
sub_copy = original[:2].copy() 

In [68]:
sub_copy

array([[5, 2, 1],
       [5, 1, 3]])

In [69]:
sub_copy_2 = original[:2,:2]

In [70]:
sub_copy_2

array([[5, 2],
       [5, 1]])

In [75]:
# Indexing and Slicing
# slice = start,stop,step
a = np.arange(10)

In [76]:
s = slice(1,7,2)

In [87]:
a[s]

array([1, 3, 5])

In [89]:
b = a[s]

In [90]:
print(b)

[1 3 5]


In [94]:
a = np.random.randint(1,10,size=(5,5))

In [95]:
# Accessing Array
a

array([[8, 3, 6, 8, 3],
       [6, 1, 3, 5, 6],
       [4, 7, 9, 3, 1],
       [5, 3, 8, 5, 7],
       [5, 3, 9, 2, 1]])

In [96]:
# Accessing 3rd row
a[2]

array([4, 7, 9, 3, 1])

In [98]:
# Accessing 3rd Row and 3rd element
a[2][2]

array([4, 7, 9, 3, 1])

In [102]:
# Accessing rows 2 and 3
a[2:4]

array([[4, 7, 9, 3, 1],
       [5, 3, 8, 5, 7]])

In [100]:
# To access 3rd Column
a[:,2]

array([6, 3, 9, 8, 9])

In [101]:
# Accessing 3rd column 3rd element
a[:,2][2]

9

In [103]:
# Accessing columns 3 and 4
a[:,2:4]

array([[6, 8],
       [3, 5],
       [9, 3],
       [8, 5],
       [9, 2]])

In [104]:
# To find the total elements of the array
a.size

25

In [105]:
# It returns Dimension of the array
a.ndim

2

In [107]:
x = np.array([[1,2,3],[4,5,6]])

In [108]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
# To get one dimension array
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [111]:
a = np.arange(1,10)

In [112]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
a.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [114]:
a.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [118]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
b = a.reshape(3,3)

In [122]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
b.ndim

2

In [124]:
b.shape

(3, 3)